const GET_ONE_COUNTRY = 'GET_ONE_COUNTRY';
const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
const GET_COUNTRY_QUERY = 'GET_COUNTRY_QUERY';
const GET_FILTER_TYPE = 'GET_FILTER_TYPE';
const GET_ORDER_PARAM = 'GET_ORDER_PARAM';

module.exports = {
    GET_ALL_COUNTRIES,
    GET_COUNTRY_QUERY,
    GET_ONE_COUNTRY,
    CREATE_ACTIVITY,
    GET_FILTER_TYPE,
    GET_ORDER_PARAM
}